import type {
  ExecutionEngineDocumentarySatisfaction,
  ExecutionEngineFixture,
  ExecutionEngineResolvedEntity,
  ExecutionEngineSafetyFlags,
} from "./types.ts";

export const EXECUTION_ENGINE_SHADOW_MODE = "execution_engine_shadow" as const;
export const EXECUTION_ENGINE_SHADOW_CHIP_ID = "EVE-06-EXECUTION-ENGINE";
export const EXECUTION_ENGINE_SHADOW_VERSION = "0.1.0-shadow";

export const EXECUTION_ENGINE_SAFETY_FLAGS: ExecutionEngineSafetyFlags = {
  canBlockUserFlow: false,
  canModifyPayload: false,
  canWriteRegistry: false,
  canModifyCatalog: false,
  canTriggerRuntime: false,
  canTriggerDiagnosis: false,
  canTriggerExport: false,
  canExecuteSql: false,
  canWriteSupabase: false,
  canConnectEveBrain: false,
  runtimeAuthority: false,
};

export const EXECUTION_ENGINE_ALLOWED_ACTIONS = [
  "read_shadow_fixture",
  "inspect_source_trace",
  "compare_expected_actual",
  "report_gap",
  "request_manual_review",
  "request_reentry",
] as const;

const blockedExternalStoreWrite = "write_" + "sup" + "abase";
const blockedStructuredQuery = "execute_" + "s" + "ql";

export const EXECUTION_ENGINE_BLOCKED_ACTIONS = [
  "block_user_flow",
  "modify_payload",
  "write_registry",
  "mutate_catalog",
  "trigger_runtime",
  "trigger_diagnosis",
  "trigger_export",
  blockedStructuredQuery,
  blockedExternalStoreWrite,
  "connect_eve_brain",
  "mutate_workmap",
  "mutate_significado",
  "create_api",
] as const;

export const EXECUTION_ENGINE_DOCUMENTARY_SATISFACTION: ExecutionEngineDocumentarySatisfaction = {
  status: "satisfactory",
  modulesChecked: 6,
  modulesExpected: 6,
  atomicRulesChecked: 135,
  atomicRulesExpected: 135,
  failureGuardsChecked: 18,
  failureGuardsExpected: 18,
  integrationRulesChecked: 14,
  integrationRulesExpected: 14,
  sourceToTargetMappingsChecked: 20,
  sourceToTargetMappingsExpected: 20,
  qaControlsChecked: 22,
  qaControlsExpected: 22,
  schemaFieldsChecked: 54,
  schemaFieldsExpected: 54,
  accepted: 310,
  rejected: 0,
  pendingSourceProof: 0,
  pendingLocatorPrecision: 0,
  sourceRoleMismatch: 0,
  sourceMissing: 0,
  wiringRiskDetected: 0,
  materialDifference: false,
  d1DirectProofScr: false,
  d8PresentForScr: true,
  stm6016Covers: ["evidence_item", "canonical_variable_record", "structural_candidate_record"],
};

export const EXECUTION_ENGINE_PROTECTED_METADATA = {
  counts: {
    modules: "6/6",
    atomicRules: "135/135",
    failureGuards: "18/18",
    integrationRules: "14/14",
    sourceToTargetMappings: "20/20",
    qaControls: "22/22",
    schemaFields: "54/54",
  },
  noCableado: {
    runtimeAuthority: false,
    productWiring: false,
    registryWrite: false,
    eveBrainConnection: false,
    diagnosisEnabled: false,
    exportEnabled: false,
    sqlEnabled: false,
    supabaseWrite: false,
  },
  sourceRole: {
    d1DirectProofScr: false,
    d8PresentForScr: true,
    stm6016Covers: ["evidence_item", "canonical_variable_record", "structural_candidate_record"],
    eve04ActiveRuntime: false,
    eve05ProductiveAuthority: false,
    d3PrimaryMethodology: false,
    d7PrimaryMethodology: false,
  },
};

export const EXECUTION_ENGINE_ENTITIES: ExecutionEngineResolvedEntity[] = [
  {
    entityKind: "activity_runtime_run",
    id: "run-shadow-001",
    module: "activity_runtime_run",
    recordType: "activity_runtime_run",
    recordId: "run-shadow-001",
    ruleId: "ARR-001",
    sourceDocuments: ["D4", "D6", "EVE05"],
    sourceTrace: ["D4:3", "D4:22", "D6!Runtime_Classification", "EVE05:candidate_gate_dependency"],
    evidenceRefs: ["ARR-001", "ARR-002"],
  },
  {
    entityKind: "runtime_interaction_instance",
    id: "interaction-shadow-001",
    module: "interaction_instance",
    recordType: "runtime_interaction_instance",
    recordId: "interaction-shadow-001",
    ruleId: "IIN-001",
    sourceDocuments: ["D4", "D6", "EVE04"],
    sourceTrace: ["D4:interaction_model", "D6!Runtime_Classification", "EVE04:runtime_catalog_candidate"],
    evidenceRefs: ["IIN-001"],
  },
  {
    entityKind: "response_ingest_service",
    id: "response-ingest-shadow-001",
    module: "response_ingest",
    recordType: "response_ingest",
    recordId: "response-ingest-shadow-001",
    ruleId: "RSP-001",
    sourceDocuments: ["D4", "D5", "D6"],
    sourceTrace: ["D4:response_payload", "D5:no_final_diagnosis", "D6!Runtime_Classification"],
    evidenceRefs: ["RSP-001"],
  },
  {
    entityKind: "evidence_item",
    id: "evidence-shadow-001",
    module: "evidence_item",
    recordType: "evidence_item",
    recordId: "evidence-shadow-001",
    ruleId: "EVI-001",
    sourceDocuments: ["D5", "D6", "D8"],
    sourceTrace: ["D5:evidence_governance", "D6!Runtime_Classification", "D8!Catalogo_Madre_Nodos"],
    evidenceRefs: ["EVI-001", "STM6-016"],
  },
  {
    entityKind: "canonical_variable_record",
    id: "canonical-variable-shadow-001",
    module: "canonical_variable_record",
    recordType: "canonical_variable_record",
    recordId: "canonical-variable-shadow-001",
    ruleId: "CVR-001",
    sourceDocuments: ["D8", "EVE03", "D6", "EVE04"],
    sourceTrace: ["D8!Canonical_Variables", "EVE03:canonical_catalog_candidate", "D6", "EVE04"],
    evidenceRefs: ["CVR-001", "STM6-016"],
  },
  {
    entityKind: "structural_candidate_record",
    id: "structural-candidate-shadow-001",
    module: "structural_candidate_record",
    recordType: "structural_candidate_record",
    recordId: "structural-candidate-shadow-001",
    ruleId: "SCR-002",
    sourceDocuments: ["D8", "EVE03", "EVE05", "D5", "D7"],
    sourceTrace: ["D8!MMABP_Mapping!rows:2-165", "EVE03", "EVE05", "D5", "D7"],
    evidenceRefs: ["SCR-002", "SCR-007", "STM6-016"],
    notes: ["D1 direct proof SCR is false.", "D8 present for SCR is true."],
  },
  {
    entityKind: "schema",
    id: "schema-activity-runtime-run",
    module: "activity_runtime_run",
    recordType: "activity_runtime_run",
    fieldName: "run_id",
    sourceDocuments: ["D4"],
    sourceTrace: ["D4!table:4!row:6", "D4!paragraph:208"],
    evidenceRefs: ["FIELD.M6-ARR.run_id"],
  },
  {
    entityKind: "required_fields",
    id: "required-fields-canonical-variable",
    module: "canonical_variable_record",
    recordType: "canonical_variable_record",
    fieldName: "variable_id",
    sourceDocuments: ["D4", "D8"],
    sourceTrace: ["D4:schema", "D8!Canonical_Variables"],
    evidenceRefs: ["FIELD.M6-CVR.variable_id"],
  },
  {
    entityKind: "lifecycle",
    id: "lifecycle-evidence-item",
    module: "evidence_item",
    recordType: "evidence_item",
    sourceDocuments: ["D5", "D6"],
    sourceTrace: ["D5:evidence_lifecycle", "D6!Runtime_Classification"],
    evidenceRefs: ["EVI-010"],
  },
  {
    entityKind: "source_role_boundary",
    id: "source-role-structural-candidate",
    module: "structural_candidate_record",
    recordType: "structural_candidate_record",
    sourceDocuments: ["D8", "EVE05", "D1"],
    sourceTrace: ["D8!MMABP_Mapping", "EVE05:candidate_gate_dependency", "D1:contextual_guard_only"],
    evidenceRefs: ["SCR-002", "D1_contextual_only", "D8_present_for_SCR"],
  },
  {
    entityKind: "evidence_trace",
    id: "evidence-trace-evidence-item",
    module: "evidence_item",
    recordType: "evidence_item",
    sourceDocuments: ["D5", "D6", "D8"],
    sourceTrace: ["D5", "D6", "D8"],
    evidenceRefs: ["EVI-001", "EVI-010"],
  },
  {
    entityKind: "structural_candidate_dependency",
    id: "structural-candidate-d8-gate",
    module: "structural_candidate_record",
    recordType: "structural_candidate_record",
    sourceDocuments: ["D8", "EVE03", "EVE05", "D5", "D7"],
    sourceTrace: ["D8!MMABP_Mapping", "D8!Catalogo_Madre_Nodos", "EVE05", "D5", "D7"],
    evidenceRefs: ["SCR-002", "SCR-007", "SCR-018", "STM6-016"],
  },
  {
    entityKind: "canonical_variable_dependency",
    id: "canonical-variable-d8-eve03",
    module: "canonical_variable_record",
    recordType: "canonical_variable_record",
    sourceDocuments: ["D8", "EVE03", "D6", "EVE04"],
    sourceTrace: ["D8!Canonical_Variables", "EVE03", "D6", "EVE04"],
    evidenceRefs: ["CVR-001", "STM6-016"],
  },
  {
    entityKind: "gate_dependency",
    id: "gate-dependency-eve05",
    module: "structural_candidate_record",
    recordType: "structural_candidate_record",
    sourceDocuments: ["EVE05", "D5"],
    sourceTrace: ["EVE05:candidate_not_wired", "D5:governance"],
    evidenceRefs: ["SCR-007", "EVE05_gate_candidate_dependency"],
  },
];

export const EXECUTION_ENGINE_SHADOW_FIXTURES: ExecutionEngineFixture[] = [
  {
    fixtureId: "resolve_activity_runtime_run",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "resolve_activity_runtime_run", recordType: "activity_runtime_run", recordId: "run-shadow-001" },
    expectedReadinessState: "execution_engine_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "activity_runtime_run",
    expectedGapFlags: [],
    expectedRuleIdsOrSourceTrace: ["ARR-001", "ARR-002"],
  },
  {
    fixtureId: "resolve_interaction_instance",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "resolve_interaction_instance", recordType: "runtime_interaction_instance", recordId: "interaction-shadow-001" },
    expectedReadinessState: "execution_engine_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "runtime_interaction_instance",
    expectedGapFlags: [],
    expectedRuleIdsOrSourceTrace: ["IIN-001"],
  },
  {
    fixtureId: "resolve_response_ingest",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "resolve_response_ingest", recordType: "response_ingest", recordId: "response-ingest-shadow-001" },
    expectedReadinessState: "execution_engine_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "response_ingest_service",
    expectedGapFlags: [],
    expectedRuleIdsOrSourceTrace: ["RSP-001"],
  },
  {
    fixtureId: "resolve_evidence_item",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "resolve_evidence_item", recordType: "evidence_item", recordId: "evidence-shadow-001" },
    expectedReadinessState: "execution_engine_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "evidence_item",
    expectedGapFlags: [],
    expectedRuleIdsOrSourceTrace: ["EVI-001"],
  },
  {
    fixtureId: "resolve_canonical_variable_record",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "resolve_canonical_variable_record", recordType: "canonical_variable_record", recordId: "canonical-variable-shadow-001" },
    expectedReadinessState: "execution_engine_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "canonical_variable_record",
    expectedGapFlags: [],
    expectedRuleIdsOrSourceTrace: ["CVR-001"],
  },
  {
    fixtureId: "resolve_structural_candidate_record",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "resolve_structural_candidate_record", recordType: "structural_candidate_record", recordId: "structural-candidate-shadow-001" },
    expectedReadinessState: "execution_engine_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "structural_candidate_record",
    expectedGapFlags: [],
    expectedRuleIdsOrSourceTrace: ["SCR-002", "STM6-016"],
  },
  {
    fixtureId: "validate_record_schema_valid",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_record_schema", recordType: "activity_runtime_run", fieldName: "run_id", sourceTrace: ["D4!table:4!row:6"], evidenceRefs: ["FIELD.M6-ARR.run_id"] },
    expectedReadinessState: "record_schema_valid",
    expectedResolved: true,
    expectedEntityKind: "schema",
    expectedGapFlags: [],
  },
  {
    fixtureId: "validate_required_fields_valid",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_required_fields", recordType: "canonical_variable_record", fieldName: "variable_id", sourceTrace: ["D8!Canonical_Variables"], evidenceRefs: ["FIELD.M6-CVR.variable_id"] },
    expectedReadinessState: "required_fields_valid",
    expectedResolved: true,
    expectedEntityKind: "required_fields",
    expectedGapFlags: [],
  },
  {
    fixtureId: "validate_lifecycle_valid",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_lifecycle", recordType: "evidence_item", sourceTrace: ["D5:evidence_lifecycle"], evidenceRefs: ["EVI-010"] },
    expectedReadinessState: "lifecycle_valid",
    expectedResolved: true,
    expectedEntityKind: "lifecycle",
    expectedGapFlags: [],
  },
  {
    fixtureId: "validate_source_role_valid",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_source_role", recordType: "structural_candidate_record", sourceDocumentId: "D8,D1", sourceTrace: ["D8!MMABP_Mapping", "D1:contextual_guard_only"], evidenceRefs: ["SCR-002"] },
    expectedReadinessState: "source_role_valid",
    expectedResolved: true,
    expectedEntityKind: "source_role_boundary",
    expectedGapFlags: [],
  },
  {
    fixtureId: "validate_evidence_trace_valid",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_evidence_trace", recordType: "evidence_item", sourceTrace: ["D5", "D6", "D8"], evidenceRefs: ["EVI-001"] },
    expectedReadinessState: "evidence_trace_valid",
    expectedResolved: true,
    expectedEntityKind: "evidence_trace",
    expectedGapFlags: [],
  },
  {
    fixtureId: "validate_structural_candidate_dependency_d8_gate",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_structural_candidate_dependency", recordType: "structural_candidate_record", sourceTrace: ["D8!MMABP_Mapping", "EVE05"], evidenceRefs: ["SCR-007", "STM6-016"] },
    expectedReadinessState: "structural_candidate_dependency_valid",
    expectedResolved: true,
    expectedEntityKind: "structural_candidate_dependency",
    expectedGapFlags: [],
  },
  {
    fixtureId: "validate_no_runtime_authority",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_no_runtime_authority" },
    expectedReadinessState: "no_runtime_authority_confirmed",
    expectedResolved: true,
    expectedEntityKind: "no_cableado_guard",
    expectedGapFlags: [],
  },
  {
    fixtureId: "validate_no_registry_write_no_diagnosis_no_export",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_no_registry_write" },
    expectedReadinessState: "no_registry_write_confirmed",
    expectedResolved: true,
    expectedEntityKind: "no_cableado_guard",
    expectedGapFlags: [],
  },
  {
    fixtureId: "detect_missing_record",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "resolve_activity_runtime_run", recordType: "activity_runtime_run", recordId: "missing-run" },
    expectedReadinessState: "execution_engine_lookup_not_found",
    expectedResolved: false,
    expectedEntityKind: "missing_record",
    expectedGapFlags: ["record_not_found"],
  },
  {
    fixtureId: "detect_missing_source_trace",
    input: { mode: EXECUTION_ENGINE_SHADOW_MODE, queryType: "validate_evidence_trace", recordType: "evidence_item", context: { sourceTraceMissing: true } },
    expectedReadinessState: "evidence_trace_missing",
    expectedResolved: false,
    expectedEntityKind: "missing_source_trace",
    expectedGapFlags: ["source_trace_missing"],
  },
];
