export type CanonicalVariableAlias = {
  sourceVariable: string;
  targetVariable: string;
  blockId: string;
  reason: string;
};

export const CAPA1_V2_1_INSTRUMENT_VERSION = "CAPA1_V2_1";

export const CANONICAL_DERIVATION_VERSION = "capa1_v2_1";

export const TRANSDUCTION_CANONICAL_VARIABLES_BY_BLOCK = {
  block_0_5: [
    "beneficiario_final_0_5_1",
    "afectado_final_0_5_1a",
    "relacion_beneficiario_afectado_0_5_1_rel",
    "beneficio_vs_dano_distribucion_0_5_1b",
    "claridad_beneficiario_0_5_1c",
    "claridad_afectado_0_5_1d",
    "scene_macro_process",
    "scene_enabled_milestone",
    "scene_priority_source_normal",
    "scene_priority_source_disruptive",
  ],
  block_1: [
    "trigger_source",
    "trigger_type",
    "trigger_frequency",
    "trigger_pattern",
    "trigger_clarity",
    "trigger_channel",
    "trigger_preconditions",
    "trigger_exception_exists",
    "trigger_exception_description",
  ],
  block_2: [
    "objeto_tipo",
    "sujeto_tipo",
    "accion_tipo",
    "dimension_dominante",
    "ranking_dimensiones",
    "atributos_objeto_cambian",
    "atributos_sujeto_cambian",
    "atributos_accion_cambian",
    "transformation_magnitude",
    "transformation_causality",
    "transformation_state_initial",
    "transformation_state_final",
    "transformation_iterations",
    "transformation_iteration_count",
    "transformation_exception_exists",
    "transformation_exception_type",
    "transformation_hidden_changes",
  ],
  block_3: [
    "output_object",
    "receiver_immediate",
    "receiver_nature",
    "receiver_delay_consequence",
    "next_step_of_receiver",
    "secondary_receivers",
    "validation_rule",
    "delivery_channel",
    "delivery_frequency",
    "delivery_failure_exists",
    "delivery_failure_type",
    "receiver_feedback",
  ],
  block_4: [
    "dependency_previous",
    "dependency_next",
    "wait_time_typical",
    "time_event_exists",
    "deadlock_risk",
    "deadlock_resolution",
    "iteration_pattern",
    "alternative_paths",
    "parallelism_pattern",
    "hidden_subprocess",
    "real_vs_official_sequence",
    "blocking_impact",
    "bottleneck_type",
    "flow_deviation_frequency",
  ],
  block_5: [
    "dimension_dominante",
    "naturaleza_actividad_5_0",
    "capacidad_nominal_5_1",
    "capacidad_real_5_2",
    "brecha_capacidad_5_3",
    "recursos_personas_5_4",
    "recursos_sistemas_5_5",
    "recursos_tiempo_5_6",
    "recursos_personas_requeridas_5_7",
    "recursos_tiempo_requerido_5_8",
    "discrecionalidad_5_9",
    "constre\u00f1imientos_5_10",
    "compensacion_5_11",
    "variedad_residual_5_12",
    "variedad_residual_destino_5_13",
    "resource_bargain_5_14",
  ],
  block_6: [
    "workaround_used",
    "workaround_types",
    "retrabajo_presente",
    "retrabajo_descripcion",
    "informacion_faltante",
    "informacion_faltante_accion",
    "regla_informal",
    "regla_informal_conocida",
    "sacrificio_humano",
    "desgaste_acumulado",
    "costo_percibido",
    "frase_trinchera",
    "patron_repetitivo",
    "absorcion_variedad_residual",
    "sintesis_principal",
  ],
  block_7: [
    "preclassification_scene_type",
    "preclassification_chain_position",
    "preclassification_vsm_role",
    "preclassification_ahe_signal",
    "preclassification_mission_suggested",
    "confidence_level",
    "confidence_score",
    "confidence_reasoning",
    "user_confirmation",
    "user_correction",
    "user_clarification",
  ],
} as const;

export const TRANSDUCTION_CANONICAL_ALIASES: readonly CanonicalVariableAlias[] =
  [
    {
      sourceVariable: "scene_functional_client",
      targetVariable: "beneficiario_final_0_5_1",
      blockId: "block_0_5",
      reason: "Transduction contract name for final beneficiary.",
    },
    {
      sourceVariable: "scene_failure_affected_actor",
      targetVariable: "afectado_final_0_5_1a",
      blockId: "block_0_5",
      reason: "Transduction contract name for affected actor.",
    },
    {
      sourceVariable: "scene_beneficiary_failure_relation",
      targetVariable: "relacion_beneficiario_afectado_0_5_1_rel",
      blockId: "block_0_5",
      reason: "Transduction contract name for beneficiary/affected relation.",
    },
    {
      sourceVariable: "scene_value_damage_distribution",
      targetVariable: "beneficio_vs_dano_distribucion_0_5_1b",
      blockId: "block_0_5",
      reason: "Transduction contract name for benefit/damage distribution.",
    },
    {
      sourceVariable: "scene_functional_client_clarity",
      targetVariable: "claridad_beneficiario_0_5_1c",
      blockId: "block_0_5",
      reason: "Transduction contract name for beneficiary clarity.",
    },
    {
      sourceVariable: "scene_failure_affected_actor_clarity",
      targetVariable: "claridad_afectado_0_5_1d",
      blockId: "block_0_5",
      reason: "Transduction contract name for affected actor clarity.",
    },
    {
      sourceVariable: "scene_primary_or_support_character",
      targetVariable: "scene_priority_source_normal",
      blockId: "block_0_5",
      reason: "Normal priority source is derived from primary/support character.",
    },
    {
      sourceVariable: "object_transformation_attributes",
      targetVariable: "atributos_objeto_cambian",
      blockId: "block_2",
      reason: "Transduction contract name for changed object attributes.",
    },
    {
      sourceVariable: "subject_transformation_attributes",
      targetVariable: "atributos_sujeto_cambian",
      blockId: "block_2",
      reason: "Transduction contract name for changed subject attributes.",
    },
    {
      sourceVariable: "action_transformation_attributes",
      targetVariable: "atributos_accion_cambian",
      blockId: "block_2",
      reason: "Transduction contract name for changed action attributes.",
    },
    {
      sourceVariable: "transformation_dimensions_selected",
      targetVariable: "ranking_dimensiones",
      blockId: "block_2",
      reason: "Selected dimensions seed the dimension ranking.",
    },
    {
      sourceVariable: "transformation_cycles_exist",
      targetVariable: "transformation_iterations",
      blockId: "block_2",
      reason: "Transduction contract name for transformation iterations.",
    },
    {
      sourceVariable: "transformation_cycle_count",
      targetVariable: "transformation_iteration_count",
      blockId: "block_2",
      reason: "Transduction contract name for iteration count.",
    },
    {
      sourceVariable: "primary_receiver",
      targetVariable: "receiver_immediate",
      blockId: "block_3",
      reason: "Transduction contract name for direct receiver.",
    },
    {
      sourceVariable: "receiver_type",
      targetVariable: "receiver_nature",
      blockId: "block_3",
      reason: "Transduction contract name for receiver nature.",
    },
    {
      sourceVariable: "receiver_impact",
      targetVariable: "receiver_delay_consequence",
      blockId: "block_3",
      reason: "Receiver impact represents consequence of delayed/bad output.",
    },
    {
      sourceVariable: "next_step_after_output",
      targetVariable: "next_step_of_receiver",
      blockId: "block_3",
      reason: "Transduction contract name for receiver next step.",
    },
    {
      sourceVariable: "quality_criteria",
      targetVariable: "validation_rule",
      blockId: "block_3",
      reason: "Transduction contract name for validation rule.",
    },
    {
      sourceVariable: "delivery_mechanism",
      targetVariable: "delivery_channel",
      blockId: "block_3",
      reason: "Transduction contract name for delivery channel.",
    },
    {
      sourceVariable: "delivery_exception_exists",
      targetVariable: "delivery_failure_exists",
      blockId: "block_3",
      reason: "Transduction contract name for delivery failure existence.",
    },
    {
      sourceVariable: "delivery_failure_normal_response",
      targetVariable: "receiver_feedback",
      blockId: "block_3",
      reason: "Normal response is the closest captured feedback signal.",
    },
    {
      sourceVariable: "wait_time",
      targetVariable: "wait_time_typical",
      blockId: "block_4",
      reason: "Transduction contract name for typical wait time.",
    },
    {
      sourceVariable: "route_alternatives",
      targetVariable: "alternative_paths",
      blockId: "block_4",
      reason: "Transduction contract name for alternative paths.",
    },
    {
      sourceVariable: "parallelism_type",
      targetVariable: "parallelism_pattern",
      blockId: "block_4",
      reason: "Transduction contract name for parallelism pattern.",
    },
    {
      sourceVariable: "blockage_impact",
      targetVariable: "blocking_impact",
      blockId: "block_4",
      reason: "Transduction contract name for blocking impact.",
    },
    {
      sourceVariable: "bottleneck",
      targetVariable: "bottleneck_type",
      blockId: "block_4",
      reason: "Transduction contract name for bottleneck type.",
    },
    {
      sourceVariable: "deviation_frequency",
      targetVariable: "flow_deviation_frequency",
      blockId: "block_4",
      reason: "Transduction contract name for flow deviation frequency.",
    },
    {
      sourceVariable: "capacidad_nominal",
      targetVariable: "capacidad_nominal_5_1",
      blockId: "block_5",
      reason: "Transduction contract name for nominal capacity.",
    },
    {
      sourceVariable: "capacidad_real",
      targetVariable: "capacidad_real_5_2",
      blockId: "block_5",
      reason: "Transduction contract name for real capacity.",
    },
    {
      sourceVariable: "recursos_personas",
      targetVariable: "recursos_personas_5_4",
      blockId: "block_5",
      reason: "Transduction contract name for people resources.",
    },
    {
      sourceVariable: "recursos_sistemas",
      targetVariable: "recursos_sistemas_5_5",
      blockId: "block_5",
      reason: "Transduction contract name for systems resources.",
    },
    {
      sourceVariable: "recursos_tiempo",
      targetVariable: "recursos_tiempo_5_6",
      blockId: "block_5",
      reason: "Transduction contract name for time resources.",
    },
    {
      sourceVariable: "recursos_requeridos",
      targetVariable: "recursos_personas_requeridas_5_7",
      blockId: "block_5",
      reason: "Closest captured field for required extra resources.",
    },
    {
      sourceVariable: "discrecionalidad",
      targetVariable: "discrecionalidad_5_9",
      blockId: "block_5",
      reason: "Transduction contract name for discretion.",
    },
    {
      sourceVariable: "constre\u00f1imientos",
      targetVariable: "constre\u00f1imientos_5_10",
      blockId: "block_5",
      reason: "Transduction contract name for constraints.",
    },
    {
      sourceVariable: "resource_bargain",
      targetVariable: "resource_bargain_5_14",
      blockId: "block_5",
      reason: "Transduction contract name for resource bargain.",
    },
    {
      sourceVariable: "absorbed_cases",
      targetVariable: "variedad_residual_5_12",
      blockId: "block_5",
      reason: "Absorbed cases are a captured residual variety signal.",
    },
    {
      sourceVariable: "rework_present",
      targetVariable: "retrabajo_presente",
      blockId: "block_6",
      reason: "Transduction contract name for rework presence.",
    },
    {
      sourceVariable: "rework_description",
      targetVariable: "retrabajo_descripcion",
      blockId: "block_6",
      reason: "Transduction contract name for rework description.",
    },
    {
      sourceVariable: "missing_information",
      targetVariable: "informacion_faltante",
      blockId: "block_6",
      reason: "Transduction contract name for missing information.",
    },
    {
      sourceVariable: "missing_information_compensation",
      targetVariable: "informacion_faltante_accion",
      blockId: "block_6",
      reason: "Transduction contract name for missing information action.",
    },
    {
      sourceVariable: "informal_rule_exists",
      targetVariable: "regla_informal_conocida",
      blockId: "block_6",
      reason: "Transduction contract name for known informal rule.",
    },
    {
      sourceVariable: "informal_rule",
      targetVariable: "regla_informal",
      blockId: "block_6",
      reason: "Transduction contract name for informal rule.",
    },
    {
      sourceVariable: "human_sacrifice",
      targetVariable: "sacrificio_humano",
      blockId: "block_6",
      reason: "Transduction contract name for human sacrifice.",
    },
    {
      sourceVariable: "wear_accumulated",
      targetVariable: "desgaste_acumulado",
      blockId: "block_6",
      reason: "Transduction contract name for accumulated wear.",
    },
    {
      sourceVariable: "effort_cost",
      targetVariable: "costo_percibido",
      blockId: "block_6",
      reason: "Transduction contract name for perceived effort cost.",
    },
    {
      sourceVariable: "trench_phrase",
      targetVariable: "frase_trinchera",
      blockId: "block_6",
      reason: "Transduction contract name for trench phrase.",
    },
    {
      sourceVariable: "repetitive_failure_pattern",
      targetVariable: "patron_repetitivo",
      blockId: "block_6",
      reason: "Transduction contract name for repetitive pattern.",
    },
    {
      sourceVariable: "residual_variety_absorption",
      targetVariable: "absorcion_variedad_residual",
      blockId: "block_6",
      reason: "Transduction contract name for residual variety absorption.",
    },
    {
      sourceVariable: "human_compensation_visibility",
      targetVariable: "sintesis_principal",
      blockId: "block_6",
      reason: "Closest captured synthesis signal for compensation visibility.",
    },
  ] as const;

