// Generated by scripts/eve/official-control-panel/r4/extract-r4-source-criteria-from-docx.mjs
// Source DOCX SHA-256: 8d18675cfbd0f370ddba5391313d2558703266ed9d67123319dc31ffb477dff2
export type R4CriterionId =
  | "CP-001"
  | "CP-002"
  | "CP-003"
  | "CP-004"
  | "CP-005"
  | "CP-006"
  | "CP-007"
  | "CP-008"
  | "CP-009"
  | "CP-010"
  | "CP-011"
  | "CP-012"
  | "CP-013"
  | "UX-001"
  | "UX-002"
  | "UX-003"
  | "UX-004"
  | "SEC-001"
  | "A11Y-001";

export type R4CriterionDefinition = {
  id: R4CriterionId;
  literalText: string;
  literalTextSha256: string;
  rectorSection: string;
  semanticObligations: string[];
  relatedFixtureIds: string[];
};

export const R4_CRITERIA: R4CriterionDefinition[] = [
  {"id":"CP-001","literalText":"La pantalla abre en Empresa Cliente.","literalTextSha256":"e4dcddc845375503ae9a9f7cc9c1923bcbf49884f3e450c41fd75d3a454e2c2c","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-001 con prueba positiva y negativa"],"relatedFixtureIds":["FX-01"]},
  {"id":"CP-002","literalText":"X funciona sin Y; Y funciona sin X.","literalTextSha256":"fa197f126bfcae0992ca2059bf9c362d3f8070100671f761ebc0b17cb07e318a","rectorSection":"§22.1","semanticObligations":["Demostrar X visible y operativo aunque Y no sea evaluable","Demostrar Y visible y operativo aunque X no sea evaluable","Comprobar ausencia de fatal global en ambos sentidos"],"relatedFixtureIds":["FX-01"]},
  {"id":"CP-003","literalText":"La intersección X/Y no inventa dependencia.","literalTextSha256":"b668144c5596037ad573740d75aa1576f6278b6225dd994c76841809ea79f201","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-003 con prueba positiva y negativa"],"relatedFixtureIds":["FX-01"]},
  {"id":"CP-004","literalText":"P-SUP-01 está visible.","literalTextSha256":"345894dc85cd3b36a467111be5f4976733814c0a042074cff1b8e4277efd2b7a","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-004 con prueba positiva y negativa"],"relatedFixtureIds":["FX-01"]},
  {"id":"CP-005","literalText":"P-SUP-03/04/05 muestran badge MANUAL.","literalTextSha256":"9563b91306034b5a4bd36d8e38aa5b8c1b545643f12a51edef9bf810285dfd6f","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-005 con prueba positiva y negativa"],"relatedFixtureIds":["FX-08"]},
  {"id":"CP-006","literalText":"Ningún output manual se marca alcanzado sin aceptación auditada.","literalTextSha256":"e61cf7fded81bb492803ea31cba8bbc7cabf0b530ff8481814f971344d91d2d2","rectorSection":"§22.1","semanticObligations":["No marcar output manual como alcanzado sin aceptación auditada","Vincular artefacto enviado y artefacto aceptado","Conservar actor, auditRef e historial append-only"],"relatedFixtureIds":["FX-08"]},
  {"id":"CP-007","literalText":"La jerarquía usuario -> rol -> actividad es navegable.","literalTextSha256":"3ea045b66e566584d98654dbf3d31e5e43c31652f0e0a387888eea5153d1536b","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-007 con prueba positiva y negativa"],"relatedFixtureIds":["FX-02"]},
  {"id":"CP-008","literalText":"No se fusionan usuarios y roles funcionales.","literalTextSha256":"cab9a25b217776395bc5e0e48d126bd525b2f409d5c3cb07732499fe6a7904fb","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-008 con prueba positiva y negativa"],"relatedFixtureIds":["FX-02"]},
  {"id":"CP-009","literalText":"Actividades no primarias permanecen visibles como contexto.","literalTextSha256":"2f2b86818b37a4810b1c757c1a919c368be90f64c68779498d8d386fc8d55938","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-009 con prueba positiva y negativa"],"relatedFixtureIds":["FX-04"]},
  {"id":"CP-010","literalText":"B0.5 y B1..B7 aparecen individualmente.","literalTextSha256":"a9764e1293decfcc74a70abd10c7c44c742a185fba726b49e25fafd00e975416","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-010 con prueba positiva y negativa"],"relatedFixtureIds":["FX-07"]},
  {"id":"CP-011","literalText":"Readiness prevalece sobre porcentaje.","literalTextSha256":"95df16ce4746761e74cc04d59b4de543d568f2d0e71f364f427d1eff3c5afd40","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-011 con prueba positiva y negativa"],"relatedFixtureIds":["FX-05"]},
  {"id":"CP-012","literalText":"P-SUP-07/08 evalúa conformance antes de consistency.","literalTextSha256":"7a5ff373afc42abbb0b222522a70c0c25fe53d2e6a52653492b1db4ae2d064e6","rectorSection":"§22.1","semanticObligations":["Completar conformance antes de iniciar consistency","Bloquear consistency antes de conformance completada","Conservar orden temporal en ledger"],"relatedFixtureIds":["FX-09"]},
  {"id":"CP-013","literalText":"P-SUP-09 está bloqueado si ACA no está Satisfied.","literalTextSha256":"f259a881f497ed5af97608a1cf345a9fd9000a8787dac440c720f3431fe93cbf","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio CP-013 con prueba positiva y negativa"],"relatedFixtureIds":["FX-10"]},
  {"id":"UX-001","literalText":"La trayectoria cubre todas las pantallas visibles y checkpoints.","literalTextSha256":"8a8517d748967b4ac2efc00a3b7f1ccd5c361a8f46f69c5c44793fae61f4e372","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio UX-001 con prueba positiva y negativa"],"relatedFixtureIds":["FX-11"]},
  {"id":"UX-002","literalText":"El usuario puede recibir soporte sin edición de respuestas.","literalTextSha256":"de098a907a10cbdad4909087720434bf6100fa9d1fee93b1eade0e4fcca971d1","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio UX-002 con prueba positiva y negativa"],"relatedFixtureIds":["FX-11"]},
  {"id":"UX-003","literalText":"Toda intervención exige capability y audit_ref.","literalTextSha256":"4c2891b32136c09bee423edbe44f79b5b87461a815a2b2ae7d8ae52686ec7e06","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio UX-003 con prueba positiva y negativa"],"relatedFixtureIds":["FX-11"]},
  {"id":"UX-004","literalText":"Tiempo/abandono no se interpreta como diagnóstico.","literalTextSha256":"e63ce486868cdabd992e84439dded3d93a04070c4f50b881ab60b15531f7a36c","rectorSection":"§22.1","semanticObligations":["Demostrar materialmente el criterio UX-004 con prueba positiva y negativa"],"relatedFixtureIds":["FX-11"]},
  {"id":"SEC-001","literalText":"El frontend no usa service_role ni DB directa.","literalTextSha256":"d27e1bd17a83a81ea90641bd374282c5463ad45107f1b34277388570d0e55fc9","rectorSection":"§22.1","semanticObligations":["Escanear fuente frontend sin service_role ni DB directa","Escanear bundle cliente construido","Validar red real sin llamadas directas a rest/rpc privilegiado","Probar auditor contra fixture negativo aislado"],"relatedFixtureIds":["FX-01","FX-11"]},
  {"id":"A11Y-001","literalText":"Todos los estados tienen texto e icono.","literalTextSha256":"2a42f3289b6ef5b9367e23b1cfaacac2891e9324c7e15ea5f92790ea5429ef07","rectorSection":"§22.1","semanticObligations":["Inventariar estados visibles","Cada estado tiene texto no vacío","Cada estado tiene icono o indicador independiente de color","El auditor detecta fallas controladas"],"relatedFixtureIds":["FX-01"]},
];
