import type {
  ParallelProductionInterfaceDocumentarySatisfaction,
  ParallelProductionInterfaceFixture,
  ParallelProductionInterfaceResolvedEntity,
  ParallelProductionInterfaceSafetyFlags,
} from "./types.ts";

export const PPI_SHADOW_MODE = "parallel_production_interface_shadow" as const;
export const PPI_SHADOW_CHIP_ID = "EVE-07-PARALLEL-PRODUCTION-INTERFACE";
export const PPI_SHADOW_VERSION = "0.1.2-candidate-shadow";

export const PPI_SAFETY_FLAGS: ParallelProductionInterfaceSafetyFlags = {
  canBlockProductiveUserFlow: false,
  canModifyPayload: false,
  canWriteRegistry: false,
  canTriggerExport: false,
  canTriggerParallelProduction: false,
  canTriggerRuntime: false,
  canTriggerDiagnosis: false,
  canExecuteSql: false,
  canWriteSupabase: false,
  canConnectEveBrain: false,
  runtimeAuthority: false,
};

export const PPI_ALLOWED_ACTIONS = [
  "read_shadow_fixture",
  "inspect_source_trace",
  "compare_expected_actual",
  "report_gap",
  "request_manual_review",
  "request_reentry",
] as const;

export const PPI_BLOCKED_ACTIONS = [
  "block_productive_user_flow",
  "modify_payload",
  "write_registry",
  "trigger_export",
  "trigger_parallel_production",
  "trigger_runtime",
  "trigger_diagnosis",
  "execute_sql",
  "write_supabase",
  "connect_eve_brain",
  "mutate_workmap",
  "mutate_significado",
  "create_api",
] as const;

export const PPI_DOCUMENTARY_SATISFACTION: ParallelProductionInterfaceDocumentarySatisfaction = {
  status: "satisfactory",
  sourceProofMatrixRowsChecked: 154,
  sourceProofMatrixRowsExpected: 154,
  sourceToTargetMappingsChecked: 26,
  sourceToTargetMappingsExpected: 26,
  exbBlockersChecked: 34,
  exbBlockersExpected: 34,
  exb031Checked: true,
  exportBlockerVectorsChecked: 6,
  exportBlockerVectorsExpected: 6,
  certificationClaimsChecked: 16,
  certificationClaimsExpected: 16,
  qaRows: 258,
  accepted: 258,
  rejected: 0,
  pendingSourceProof: 0,
  pendingLocatorPrecision: 0,
  certificationClaimUnverified: 0,
  materialDifference: false,
};

export const PPI_PROTECTED_METADATA = {
  noCableado: {
    runtimeAuthority: false,
    registryWrite: false,
    productWiring: false,
    eveBrainConnection: false,
    finalExportEnabled: false,
    parallelProductionEnabled: false,
    diagnosisEnabled: false,
    sqlEnabled: false,
    supabaseWrite: false,
  },
  sourceRoles: {
    direct: ["D3", "D4", "D5", "D6", "D8", "EVE06", "EVE05", "EVE04"],
    contextual: ["EVE03", "D7"],
    methodologicalGuardOnly: ["D1"],
  },
};

export const PPI_ENTITIES: ParallelProductionInterfaceResolvedEntity[] = [
  {
    entityKind: "scr_payload_shadow_candidate",
    id: "scr-payload-reference",
    module: "scr_payload",
    payloadType: "scr_payload",
    payloadId: "scr-reference",
    sourceDocuments: ["D4", "D6", "D8"],
    sourceTrace: ["D4:payload-contract", "D6:runtime-workbook", "D8:canonical-genealogy"],
    evidenceRefs: ["STM7-SCR", "D8:Canonical_Variables"],
  },
  {
    entityKind: "evidence_bundle_shadow_candidate",
    id: "evidence-bundle-reference",
    module: "evidence_bundle_payload",
    payloadType: "evidence_bundle_payload",
    payloadId: "evidence-bundle-reference",
    sourceDocuments: ["D4", "D6", "EVE06"],
    sourceTrace: ["D4:evidence-contract", "D6:evidence-mapping", "EVE06:evidence-records"],
    evidenceRefs: ["STM7-EVIDENCE", "EVE06:evidence_item"],
  },
  {
    entityKind: "mdsb_shadow_candidate",
    id: "mdsb-reference",
    module: "mdsb_payload",
    payloadType: "mdsb_payload",
    payloadId: "mdsb-reference",
    sourceDocuments: ["D4", "D5", "D6"],
    sourceTrace: ["D4:mdsb-contract", "D5:no-diagnosis-boundary", "D6:runtime-workbook"],
    evidenceRefs: ["STM7-MDSB", "D5:diagnosis-disabled"],
  },
  {
    entityKind: "mmabp_ir_candidate_shadow",
    id: "mmabp-ir-candidate-reference",
    module: "mmabp_ir_candidate",
    payloadType: "mmabp_ir_candidate",
    payloadId: "mmabp-ir-candidate-reference",
    sourceDocuments: ["D5", "D6", "D8", "EVE06"],
    sourceTrace: ["D5:runtime-governance", "D6:ir-candidate", "D8:mmabp-mapping", "EVE06:structural-candidates"],
    evidenceRefs: ["STM7-IR", "EVE06:structural_candidate_record"],
  },
  {
    entityKind: "registry_candidate_shadow",
    id: "registry-candidate-reference",
    module: "registry_candidate",
    payloadType: "registry_candidate",
    payloadId: "registry-candidate-reference",
    sourceDocuments: ["D5", "D6", "EVE04"],
    sourceTrace: ["D5:no-registry-write", "D6:registry-candidate", "EVE04:catalog-candidate"],
    evidenceRefs: ["REGC-006", "REGC-011"],
  },
  {
    entityKind: "export_blocker_set_shadow",
    id: "export-blockers-reference",
    module: "export_blockers",
    payloadType: "export_blockers",
    payloadId: "export-blockers-reference",
    sourceDocuments: ["D4", "D5", "EVE05"],
    sourceTrace: ["D4:export-boundary", "D5:no-export", "EVE05:gate-blockers"],
    evidenceRefs: ["EXBE-013", "EXB-031"],
  },
  {
    entityKind: "payload_schema_validation",
    id: "scr-payload-schema",
    payloadType: "scr_payload",
    sourceDocuments: ["D4", "D6"],
    sourceTrace: ["D4:payload-schema", "D6:payload-fields"],
    evidenceRefs: ["SCHEMA-SCR-001"],
  },
  {
    entityKind: "source_proof_validation",
    id: "REGC-006",
    ruleId: "REGC-006",
    sourceDocuments: ["D5"],
    sourceTrace: ["D5:heading-10:table-13:row-5"],
    evidenceRefs: ["REGC-006:D5"],
  },
  {
    entityKind: "export_blocker_validation",
    id: "EXB-013",
    blockerCode: "EXB-013",
    sourceDocuments: ["EVE05"],
    sourceTrace: ["EVE05:modules.mmabp_conformance_gate.principles[4]"],
    evidenceRefs: ["EXBE-013:EVE05"],
  },
  {
    entityKind: "exb_031_boundary_validation",
    id: "EXB-031",
    blockerCode: "EXB-031",
    sourceDocuments: ["D4", "D5"],
    sourceTrace: ["D4:override-boundary", "D5:audit-required-before-export"],
    evidenceRefs: ["EXB-031:D4-D5"],
  },
  {
    entityKind: "documentary_satisfaction_summary",
    id: "PARALLEL_PRODUCTION_INTERFACE_RECORD_RULE_QA_SATISFACTORY",
    sourceDocuments: ["QA_V1_1"],
    sourceTrace: ["record-rule-source-qa-v1_1", "static-package-tests-v1"],
    evidenceRefs: ["154/154", "26/26", "34/34", "EXB-031", "258 accepted"],
  },
  {
    entityKind: "registry_boundary_validation",
    id: "registry-candidate-boundary",
    module: "registry_candidate",
    sourceDocuments: ["D5", "EVE04"],
    sourceTrace: ["D5:no-registry-write", "EVE04:catalog-candidate-not-runtime"],
    evidenceRefs: ["registryWrite=false", "runtimeAuthority=false"],
  },
  {
    entityKind: "ir_boundary_validation",
    id: "ir-candidate-boundary",
    module: "mmabp_ir_candidate",
    sourceDocuments: ["D5", "EVE06"],
    sourceTrace: ["D5:no-runtime-readiness-final", "EVE06:candidate-only"],
    evidenceRefs: ["IR-finalization-blocked", "runtimeAuthority=false"],
  },
];

export const PPI_SHADOW_FIXTURES: ParallelProductionInterfaceFixture[] = [
  {
    fixtureId: "resolve_scr_payload",
    input: { mode: PPI_SHADOW_MODE, queryType: "resolve_scr_payload", payloadType: "scr_payload" },
    expectedReadinessState: "ppi_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "scr_payload_shadow_candidate",
    expectedGapFlags: [],
    expectedBlockedActions: ["modify_payload", "write_registry", "trigger_export"],
  },
  {
    fixtureId: "resolve_evidence_bundle_payload",
    input: { mode: PPI_SHADOW_MODE, queryType: "resolve_evidence_bundle_payload", payloadType: "evidence_bundle_payload" },
    expectedReadinessState: "ppi_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "evidence_bundle_shadow_candidate",
    expectedGapFlags: [],
    expectedBlockedActions: ["write_registry", "trigger_export"],
  },
  {
    fixtureId: "resolve_mdsb_payload",
    input: { mode: PPI_SHADOW_MODE, queryType: "resolve_mdsb_payload", payloadType: "mdsb_payload" },
    expectedReadinessState: "ppi_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "mdsb_shadow_candidate",
    expectedGapFlags: [],
    expectedBlockedActions: ["trigger_diagnosis", "trigger_export"],
  },
  {
    fixtureId: "resolve_mmabp_ir_candidate",
    input: { mode: PPI_SHADOW_MODE, queryType: "resolve_mmabp_ir_candidate", payloadType: "mmabp_ir_candidate" },
    expectedReadinessState: "ppi_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "mmabp_ir_candidate_shadow",
    expectedGapFlags: [],
    expectedBlockedActions: ["trigger_runtime", "trigger_export"],
  },
  {
    fixtureId: "resolve_registry_candidate",
    input: { mode: PPI_SHADOW_MODE, queryType: "resolve_registry_candidate", payloadType: "registry_candidate" },
    expectedReadinessState: "ppi_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "registry_candidate_shadow",
    expectedGapFlags: [],
    expectedBlockedActions: ["write_registry", "trigger_runtime"],
  },
  {
    fixtureId: "resolve_export_blockers",
    input: { mode: PPI_SHADOW_MODE, queryType: "resolve_export_blockers", payloadType: "export_blockers" },
    expectedReadinessState: "ppi_lookup_ready",
    expectedResolved: true,
    expectedEntityKind: "export_blocker_set_shadow",
    expectedGapFlags: [],
    expectedBlockedActions: ["trigger_export", "trigger_parallel_production"],
  },
  {
    fixtureId: "validate_payload_schema_valid",
    input: {
      mode: PPI_SHADOW_MODE,
      queryType: "validate_payload_schema",
      payloadType: "scr_payload",
      sourceTrace: ["D4:payload-schema"],
      evidenceRefs: ["SCHEMA-SCR-001"],
    },
    expectedReadinessState: "payload_schema_valid",
    expectedResolved: true,
    expectedEntityKind: "payload_schema_validation",
    expectedGapFlags: [],
    expectedBlockedActions: ["modify_payload"],
  },
  {
    fixtureId: "validate_source_proof_valid",
    input: {
      mode: PPI_SHADOW_MODE,
      queryType: "validate_source_proof",
      ruleId: "REGC-006",
      sourceDocumentId: "D5",
      sourceTrace: ["D5:heading-10:table-13:row-5"],
      evidenceRefs: ["REGC-006:D5"],
    },
    expectedReadinessState: "source_proof_valid",
    expectedResolved: true,
    expectedEntityKind: "source_proof_validation",
    expectedGapFlags: [],
    expectedBlockedActions: ["write_registry"],
  },
  {
    fixtureId: "validate_export_blocker_valid",
    input: {
      mode: PPI_SHADOW_MODE,
      queryType: "validate_export_blocker",
      blockerCode: "EXB-013",
      sourceDocumentId: "EVE05",
    },
    expectedReadinessState: "export_blocker_valid",
    expectedResolved: true,
    expectedEntityKind: "export_blocker_validation",
    expectedGapFlags: [],
    expectedBlockedActions: ["trigger_export"],
  },
  {
    fixtureId: "validate_exb_031_override_requested_not_audited",
    input: {
      mode: PPI_SHADOW_MODE,
      queryType: "validate_exb_031",
      blockerCode: "EXB-031",
      context: { overrideRequested: true, overrideAudited: false },
    },
    expectedReadinessState: "exb_031_violation_detected",
    expectedResolved: false,
    expectedEntityKind: "exb_031_boundary_validation",
    expectedGapFlags: ["EXB_031_OVERRIDE_NOT_AUDITED"],
    expectedBlockedActions: ["trigger_export", "trigger_parallel_production"],
  },
  {
    fixtureId: "validate_exb_031_override_audited",
    input: {
      mode: PPI_SHADOW_MODE,
      queryType: "validate_exb_031",
      blockerCode: "EXB-031",
      context: { overrideRequested: true, overrideAudited: true },
    },
    expectedReadinessState: "exb_031_valid",
    expectedResolved: true,
    expectedEntityKind: "exb_031_boundary_validation",
    expectedGapFlags: [],
    expectedBlockedActions: ["trigger_export", "trigger_parallel_production"],
  },
  {
    fixtureId: "validate_no_export_no_registry_no_parallel_production",
    input: { mode: PPI_SHADOW_MODE, queryType: "validate_no_export" },
    expectedReadinessState: "no_export_confirmed",
    expectedResolved: true,
    expectedEntityKind: "safety_boundary_validation",
    expectedGapFlags: [],
    expectedBlockedActions: ["write_registry", "trigger_export", "trigger_parallel_production"],
  },
  {
    fixtureId: "validate_documentary_satisfaction",
    input: { mode: PPI_SHADOW_MODE, queryType: "validate_documentary_satisfaction" },
    expectedReadinessState: "documentary_satisfaction_confirmed",
    expectedResolved: true,
    expectedEntityKind: "documentary_satisfaction_summary",
    expectedGapFlags: [],
    expectedBlockedActions: ["write_registry", "trigger_export"],
  },
  {
    fixtureId: "detect_missing_source_proof",
    input: { mode: PPI_SHADOW_MODE, queryType: "validate_source_proof", ruleId: "UNKNOWN-RULE", sourceTrace: [], evidenceRefs: [] },
    expectedReadinessState: "source_proof_missing",
    expectedResolved: false,
    expectedEntityKind: "missing_source_proof",
    expectedGapFlags: ["SOURCE_PROOF_MISSING"],
    expectedBlockedActions: ["write_registry", "trigger_export"],
  },
  {
    fixtureId: "detect_missing_payload",
    input: { mode: PPI_SHADOW_MODE, queryType: "resolve_scr_payload", payloadId: "missing-payload" },
    expectedReadinessState: "ppi_lookup_not_found",
    expectedResolved: false,
    expectedEntityKind: "missing_payload",
    expectedGapFlags: ["PPI_LOOKUP_NOT_FOUND"],
    expectedBlockedActions: ["modify_payload", "write_registry", "trigger_export"],
  },
  {
    fixtureId: "validate_registry_candidate_boundary",
    input: { mode: PPI_SHADOW_MODE, queryType: "validate_registry_candidate_boundary", module: "registry_candidate" },
    expectedReadinessState: "registry_candidate_boundary_confirmed",
    expectedResolved: true,
    expectedEntityKind: "registry_boundary_validation",
    expectedGapFlags: [],
    expectedBlockedActions: ["write_registry", "trigger_runtime"],
  },
];
